import express from "express"; // Change
import fs from "fs"; // Change
import path from "path"; // Change
import simpleGit from "simple-git"; // Change
import { Octokit } from "@octokit/rest"; // Change
import 'dotenv/config'; // Change: Load dotenv early and correctly for ES Modules
import { fileURLToPath } from 'url'; // Added for __dirname equivalent

// Added for __dirname equivalent in ES Modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const router = express.Router();
const git = simpleGit(); // simpleGit() usually works fine without arguments if in a Git repo root
const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

const repo = process.env.GITHUB_REPO;
const username = process.env.GITHUB_USERNAME;
const projectFolderToScan = process.env.SCAN_FOLDER_PATH;

// Helper: Read all code files
function getAllCodeFiles(dir, fileList = []) {
  const files = fs.readdirSync(dir);
  files.forEach((file) => {
    const fullPath = path.join(dir, file);
    if (fs.statSync(fullPath).isDirectory()) {
      getAllCodeFiles(fullPath, fileList);
    } else if (file.endsWith(".js") || file.endsWith(".ts") || file.endsWith(".py")) {
      fileList.push(fullPath);
    }
  });
  return fileList;
}

// POST /api/scan-and-pr
router.post("/scan-and-pr", async (req, res) => {
  try {
    // Before running, ensure this is a Git repository and you're in the right directory.
    // Also, ensure the 'your-project-folder' path is correct relative to where you run the server.
    //const projectFolderToScan = path.join(__dirname, '..', 'your-project-folder'); // Adjust this path as needed
    //const projectFolderToScan = "C:\Users\HP\Desktop\FinalProject\pullrequest\Pull-request\blackbox_ai_backend_node";

    const branchName = `ai/code-scan-${Date.now()}`;
    await git.checkoutLocalBranch(branchName);

    const files = getAllCodeFiles(projectFolderToScan);
    for (let filePath of files) {
      const original = fs.readFileSync(filePath, "utf8");

      // Simulate AI fix — integrate Gemini or Deepseek here
      //const fixed = original.replace(/let /g, "let "); // e.g., dumb fix
      const fixed = original + "\n// AI reviewed\n";


      if (original !== fixed) {
        fs.writeFileSync(filePath, fixed, "utf8");
        await git.add(filePath);
      }
    }

    await git.commit("AI: Fixed code issues");
    await git.push("origin", branchName);

    // Create pull request via GitHub API
    const [owner, repoName] = repo.split("/");
    const pr = await octokit.pulls.create({
      owner,
      repo: repoName,
      title: "AI Code Scan Fixes",
      head: branchName,
      base: "main", // Or 'master' depending on your repo's default branch
      body: "This PR was generated by AI code scanning tool.",
    });

    res.json({ message: "Pull request created", prUrl: pr.data.html_url });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message });
  }
});

export default router; // Change
// AI reviewed
